sudo: false
language: cpp

os:
  - linux

cache:
  directories:
    - $HOME/.cache/yarn

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gcc-4.9-multilib
      - g++-4.9-multilib
      - zip
      - libgtk2.0-0
      - libx11-dev
      - libxkbfile-dev
      - libsecret-1-dev

before_install:
  - export GITHUB_TOKEN=$PUBLIC_GITHUB_TOKEN
  - git submodule update --init --recursive
  - nvm install 8.9.1
  - nvm use 8.9.1
  - npm i -g yarn
  # - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  # Make npm logs less verbose
  # - npm config set depth 0
  # - npm config set loglevel warn

install:
  - yarn

script:
  - node_modules/.bin/gulp electron --silent
  - node_modules/.bin/gulp compile --silent --max_old_space_size=4096
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./scripts/test.sh --coverage --reporter dot; else ./scripts/test.sh --reporter dot; fi
  - ./scripts/test-integration.sh

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then node_modules/.bin/coveralls < .build/coverage/lcov.info; fi

matrix:
  include:
    - os: linux
      env: label=hygiene
      script: node_modules/.bin/gulp hygiene
      after_success: skip

env:
  global:
    secure: I/6cLCDCdhCGo7TEvXyjqp0gYXlyQMBi3/Y3jDxpBCfbI+6B6kni1sOoI9evwGZlPQCnsEkT4bnM+QYb6qtEDVoiwBS/MB+RDXCOX8+BpfJOxGRHa2KhD+Ia2lCiE9uWMtGOgOTOmxJonZrp7Q1YamPZLG8IrIHPI1OlKLIzV61GxAem4uHNEnafYsPIXMT9wZhuW1WD/iEXUjYFCMyW6CggmyKSlHQoGKdizJkGFP5qvdtb8fqT2jZfeRRAXgizfJL4J4s3qtP7rrsg458YvrTF+VYzbOvby6PHolrc/C5iRAYUIeOhYsPUKXOri8lK6qJueASBcTS0K+kJdGz0ym6RRXA1jadzYwkYvkwqAO/vZxKEcVNrgLkeHBjzWyIfGuO9toZFeQLAP83cfTJW3kJ6ntqWjyi+YX8J01gDIq1VY00MQ+wCv+zvsbCbyJy4XOwSZN9i+NLdKKzVabr/8njttJEFekb7QdLnig8Z/YVK/1wI+ENDCxvjVRDv2kXR58Myz20HNT/F8NIZvY4+u8AX96HwkBeFxWC2HlRws5zgco+o0UJlaTNFYG1Ev64QKtcDemLqW89EXWMw5+YVFFPdmD2qHmYgymr/QLxlVJhseogEhw8+saASolNmPCq4Vw9h+vDzjCqCZiC6XKXMK8TPmEtYK7sopXitfMStx7c=
